### ISSUE TITLE
Gmail User Watch 

### ISSUE THREAD

**Issue by ponty96** [craigp/elixir-gmail#10]
So I've gone through the docs and I can't seem to find a way to watch for new messages as specified by this:
```
POST "https://www.googleapis.com/gmail/v1/users/me/watch"
Content-type: application/json

{
  topicName: "projects/myproject/topics/mytopic",
  labelIds: ["INBOX"],
}
```
https://developers.google.com/gmail/api/guides/push

**Comment by craigp** [comment]
That's because it hasn't been implemented :)

There's an "API Support" section in the README that lists everything that's covered so far. Additionally,  `watch` is a little more complicated, since it requires pubsub setup and a server application to receive webhook callbacks, so I hadn't planned to support it inside this library, but if you're keen to have a go PRs are welcome.

Alternatively, you could poll the history API for changes to the mailbox.
